'use strict';
const { z } = require('zod');
const symbol = z.string().min(1).transform((value) => value.trim().toUpperCase());
const side = z.enum(['BUY', 'SELL']);
const text = (data) => ({ content: [{ type: 'text', text: JSON.stringify(data, null, 2) }] });
function registerTradingTools(server, { client }) {
  server.registerTool('place_order', { description: 'Place a signed futures order.', inputSchema: { symbol, side, type: z.string(), quantity: z.union([z.string(), z.number()]), price: z.union([z.string(), z.number()]).optional(), reduceOnly: z.boolean().optional() } }, async (args) => text(await client.createOrder(args)));
  server.registerTool('modify_order', { description: 'Modify a signed futures order.', inputSchema: { symbol, orderId: z.number().optional(), origClientOrderId: z.string().optional(), side, quantity: z.union([z.string(), z.number()]), price: z.union([z.string(), z.number()]) } }, async (args) => text(await client.modifyOrder(args)));
  server.registerTool('cancel_order', { description: 'Cancel a signed futures order.', inputSchema: { symbol, orderId: z.number().optional(), origClientOrderId: z.string().optional() } }, async ({ symbol, orderId, origClientOrderId }) => text(await client.cancelOrder(symbol, orderId, origClientOrderId)));
  server.registerTool('cancel_all_orders', { description: 'Cancel all signed open orders for a symbol.', inputSchema: { symbol } }, async ({ symbol }) => text(await client.cancelAllOpenOrders(symbol)));
  server.registerTool('get_order', { description: 'Get a signed futures order.', inputSchema: { symbol, orderId: z.number().optional(), origClientOrderId: z.string().optional() } }, async ({ symbol, orderId, origClientOrderId }) => text(await client.getOrder(symbol, orderId, origClientOrderId)));
  server.registerTool('place_bracket', { description: 'Place entry, stop-loss, and take-profit futures orders.', inputSchema: { symbol, side, quantity: z.union([z.string(), z.number()]), entryPrice: z.union([z.string(), z.number()]).optional(), stopPrice: z.union([z.string(), z.number()]), takeProfitPrice: z.union([z.string(), z.number()]) } }, async ({ symbol, side, quantity, entryPrice, stopPrice, takeProfitPrice }) => { const exitSide = side === 'BUY' ? 'SELL' : 'BUY'; const entry = await client.createOrder({ symbol, side, type: entryPrice ? 'LIMIT' : 'MARKET', quantity, price: entryPrice, timeInForce: entryPrice ? 'GTC' : undefined }); const stop = await client.createOrder({ symbol, side: exitSide, type: 'STOP_MARKET', stopPrice, closePosition: true }); const takeProfit = await client.createOrder({ symbol, side: exitSide, type: 'TAKE_PROFIT_MARKET', stopPrice: takeProfitPrice, closePosition: true }); return text({ entry, stop, takeProfit }); });
  server.registerTool('close_position', { description: 'Close a futures position with a reduce-only market order.', inputSchema: { symbol, side, quantity: z.union([z.string(), z.number()]) } }, async ({ symbol, side, quantity }) => text(await client.createOrder({ symbol, side, type: 'MARKET', quantity, reduceOnly: true })));
  server.registerTool('get_trade_history', { description: 'Get signed trade history.', inputSchema: { symbol, limit: z.number().int().positive().max(1000).default(100) } }, async ({ symbol, limit }) => text(await client.getUserTrades(symbol, { limit })));
}
module.exports = { registerTradingTools };
